ViewERP/WebView/Controllers/VentasController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebView.Models;

namespace WebView.Controllers
{
    public class VentasController : Controller
    {
        [ERPVerificaAccount]
        public ActionResult AgregarVenta()
        {
            int idCompania = ((DO_Persona)Session["UsuarioConectado"]).idCompania;
            ViewBag.Articulos = DataManager.ConvertListDOArticuloToSelectListItem(DataManager.GetAllArticulos(idCompania));

            //Promotores

            List<DO_Persona> promotores = DataManager.GetAllPromotores(idCompania);
            promotores.Insert(0,new DO_Persona { idUsuario = 0, Nombre = "Ninguno" });

            ViewBag.Promotores = DataManager.ConvertListDoPersonaToSelectListItem(promotores);

            return View();
        }

        [HttpPost]
        public JsonResult GuardarVenta(int cantidad, DateTime fecha, int idArticulo, int idPromotor)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            DO_Persona personaConectada = ((DO_Persona)Session["UsuarioConectado"]);

            double precio = DataManager.GetPrecioMaster(idArticulo);
            double monto = cantidad * precio;

            int idVenta = DataManager.InsertVenta(idUsuario, monto, fecha);

            int r = DataManager.InsertDetailVenta(idVenta, idArticulo, cantidad, precio);

            #region Registro en almacen
            DO_Articulo articulo = DataManager.GetArticulo(idArticulo);
            
            List<DO_DetalleSalidaArticulo> articulos = new List<DO_DetalleSalidaArticulo>();
            DO_DetalleSalidaArticulo dO_DetalleSalida = new DO_DetalleSalidaArticulo();
            dO_DetalleSalida.cantidad = cantidad;
            dO_DetalleSalida.codigo = articulo.Codigo;
            dO_DetalleSalida.condicion = "NUEVO";
            dO_DetalleSalida.Descripcion = articulo.Descripcion;
            dO_DetalleSalida.idCodigo = idArticulo;
            articulos.Add(dO_DetalleSalida);

            List<DO_Almacen> almacens = DataManager.GetAllAlmacen(personaConectada.idCompania);

            int result = DataManager.InsertSalidaArticuloAlmacen(almacens[0].idAlmacen, "SALIDA VENTA", personaConectada.Usuario, articulos);

            #endregion

            //Checamos si el usuario eligió asignarla a un promotor
            if (idPromotor!= 0)
            {
                int promotorVenta = DataManager.InsertVentaPromotor(idVenta, idPromotor);
            }

            DataManager.InsertBitacora(personaConectada.Nombre + " " + personaConectada.Usuario, "Se crea un registro de venta del idArticulo:" + idArticulo + ", Con la cantidad: " + cantidad);

            var jsonResult = Json(r, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaDiaActual(string parametro)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            double venta = DataManager.GetVentaDiaActual(idUsuario);

            var jsonResult = Json(venta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaDiaActualOrganizacion(string parametro)
        {
            int idOrganizacion = ((DO_Persona)Session["UsuarioConectado"]).idOrganizacion;

            double venta = DataManager.GetVentaDiaActualOrganizacion(idOrganizacion);

            var jsonResult = Json(venta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        public JsonResult GetVentaSemanaActualOrganizacion(string parametro)
        {
            int idOrganizacion = ((DO_Persona)Session["UsuarioConectado"]).idOrganizacion;

            DO_Semana semanaActual = DataManager.GetSemanaActual();

            List<FO_Item> lista =  DataManager.GetVentaSemanalOrganizacionBySemanaByCompania(idOrganizacion, semanaActual.IdSemana);

            var jsonResult = Json(lista, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaMesActual(string parametro)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            double venta = DataManager.GetVentaMesActual(idUsuario);

            var jsonResult = Json(venta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaSemanaActual(string parametro)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            double venta = DataManager.GetVentaSemanaActual(idUsuario);

            var jsonResult = Json(venta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaSemanaActualByGerente(int idUsuario)
        {
            double venta = DataManager.GetVentaSemanaActual(idUsuario);

            var jsonResult = Json(venta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaUltimosMeses(string parametro)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            List<FO_Item> lista = DataManager.GetVentaUltimosMeses(idUsuario);

            var jsonResult = Json(lista, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaSemanalDiaria(string parametro)
        {
            int idCompania = ((DO_Persona)Session["UsuarioConectado"]).idCompania;

            DO_ChartData dO_ChartData = DataManager.GetVentaSemanalDiaria(idCompania);

            var jsonResult = Json(dO_ChartData, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaSemanalDiariaByWeek(int idSemana)
        {
            int idCompania = ((DO_Persona)Session["UsuarioConectado"]).idCompania;

            DO_ChartData dO_ChartData = DataManager.GetVentaSemanalDiaria(idCompania,idSemana);

            var jsonResult = Json(dO_ChartData, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetVentaSemanalDiariaGerente(int idCompania)
        {
            DO_ChartData dO_ChartData = DataManager.GetVentaSemanalDiaria(idCompania);

            var jsonResult = Json(dO_ChartData, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetLastVentas(string parametro)
        {
            int idCompania = ((DO_Persona)Session["UsuarioConectado"]).idCompania;

            List<DO_Ventas> lastVentas = DataManager.GetListLastVentas(idCompania);

            var jsonResult = Json(lastVentas, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetGananciaGerente(string parametro)
        {
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;

            double gananciaTotal = DataManager.GetGananciaGerenteCurrentWeek(idUsuario);

            var jsonResult = Json(gananciaTotal, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult EliminarVenta(int idVenta)
        {
            #region Se borra la venta
            DO_Ventas venta = DataManager.GetVenta(idVenta);

            DO_Persona personaConectada = ((DO_Persona)Session["UsuarioConectado"]);
            List<DO_Almacen> almacens = DataManager.GetAllAlmacen(personaConectada.idCompania);
            DO_Almacen almacen = almacens[0];

            int r = DataManager.AddExistencia(almacen.idAlmacen, venta.IdArticulo, venta.Cantidad);

            r = DataManager.DeleteVentaPromotor(idVenta);
            r = DataManager.DeleteVentaDetails(idVenta);
            r = DataManager.DeleteVenta(idVenta);
            #endregion

            var jsonResult = Json(r, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GuardarCambiosVenta(int idVenta, int cantidad, DateTime fecha, int idArticulo, int idPromotor)
        {
            #region Se borra la venta
            DO_Ventas venta = DataManager.GetVenta(idVenta);

            DO_Persona personaConectada = ((DO_Persona)Session["UsuarioConectado"]);
            List<DO_Almacen> almacens = DataManager.GetAllAlmacen(personaConectada.idCompania);
            DO_Almacen almacen = almacens[0];

            int r = DataManager.AddExistencia(almacen.idAlmacen, venta.IdArticulo, venta.Cantidad);

            r = DataManager.DeleteVentaPromotor(idVenta);
            r = DataManager.DeleteVentaDetails(idVenta);
            r = DataManager.DeleteVenta(idVenta);
            #endregion

            #region Registro venta
            int idUsuario = ((DO_Persona)Session["UsuarioConectado"]).idUsuario;
            double precio = DataManager.GetPrecioMaster(idArticulo);
            double monto = cantidad * precio;

            idVenta = DataManager.InsertVenta(idUsuario, monto, fecha);

ViewERP/WebView/Views/Ventas/AgregarVenta.cshtml
@{
    ViewBag.Title = "AgregarVenta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Ventas</h4>
                <hr />
                <div class="panel-body pb-0">
                    <div class="form-horizontal group-border stripped">

                        <div class="form-group">
                            <label for="">Fecha</label>
                            <div class="col-lg-7 col-md-6">
                                <div class="input-group date" id="datetimepicker1">
                                    <input type="text" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="fa fa-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Articulo</label>
                            <div class="col-lg-7 col-md-6">
                                <select id="cboArticulos" class="form-control modalColor" style="width:90%">
                                    @{
                                        foreach (SelectListItem articulo in ((List<SelectListItem>)ViewBag.Articulos))
                                        {
                                            <option id="@articulo.Value" value="@articulo.Value">@articulo.Text</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Promotor</label>
                            <div class="col-lg-7 col-md-6">
                                <select id="cboPromotores" class="form-control modalColor" style="width:90%">
                                    @{
                                        foreach (SelectListItem promotor in ((List<SelectListItem>)ViewBag.Promotores))
                                        {
                                            <option id="@promotor.Value" value="@promotor.Value">@promotor.Text</option>
                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Cantidad</label>
                            <div class="col-lg-7 col-md-6">
                                <input type="number" class="form-control modalColor" style="width:90%" id="txtCantidad" />
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <button class="btn btn-success" id="btnGuardarEntrada" onclick="guardarVenta()">Guardar cambios</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $('#datetimepicker1').datetimepicker({
            format: 'L'
        });
    });

    $(document).ajaxStart(function () {
        $("#btnGuardarEntrada").addClass("disabled");
        $("#btnGuardarEntrada").html("<i class=\"fa fa-refresh fa-spin\"></i>Guardando");
    });

    $(document).ajaxComplete(function () {
        $("#btnGuardarEntrada").html("Guardar");
        $("#btnGuardarEntrada").removeClass("disabled");
    });

    function guardarVenta() {
        var _fecha = $("#datetimepicker1").data("date");
        var _cantidad = $("#txtCantidad").val();
        var _idArticulo = $("#cboArticulos").val();
        var _idPromotor = $("#cboPromotores").val();

        var urlSave = '@Url.Action("GuardarVenta", "Ventas")';
        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ cantidad: _cantidad, fecha: _fecha, idArticulo: _idArticulo, idPromotor: _idPromotor }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                alert("Venta agregada correctamente");
                $("#txtCantidad").val("0");
            },
            error: function (result) {
                alert("Woops, se produjo un error");
            }
        });
    }
</script>

ViewERP/WebView/Views/Ventas/Edit.cshtml
@model WebView.Models.DO_Ventas

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Editar Venta</h4>
                <hr />
                <div class="panel-body pb-0">
                    <div class="form-horizontal group-border stripped">
                        <input type="hidden" value="@Model.IdVenta" id="txtIdVenta" />

                        <div class="form-group">
                            <label for="">Fecha</label>
                            <div class="col-lg-7 col-md-6">
                                <div class="input-group date" id="datetimepicker2">
                                    <input type="text" class="form-control" value="@Model.Fecha" />
                                    <span class="input-group-addon">
                                        <span class="fa fa-calendar"></span>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Promotor</label>
                            <div class="col-lg-7 col-md-6">
                                <select id="cboPromotores" class="form-control modalColor" style="width:90%">
                                    @{
                                        foreach (SelectListItem promotor in ((List<SelectListItem>)ViewBag.Promotores))
                                        {
                                            if (promotor.Selected)
                                            {
                                                <option selected id="@promotor.Value" value="@promotor.Value">@promotor.Text</option>
                                            }
                                            else
                                            {
                                                <option id="@promotor.Value" value="@promotor.Value">@promotor.Text</option>
                                            }

                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>Articulo</label>
                            <div class="col-lg-7 col-md-6">
                                <select id="cboArticulos" class="form-control modalColor" style="width:90%">
                                    @{
                                        foreach (SelectListItem articulo in ((List<SelectListItem>)ViewBag.Articulos))
                                        {
                                            if (articulo.Selected)
                                            {
                                                <option selected id="@articulo.Value" value="@articulo.Value">@articulo.Text</option>
                                            }
                                            else
                                            {
                                                <option id="@articulo.Value" value="@articulo.Value">@articulo.Text</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-9 col-md-9 control-label" for="">Cantidad</label>
                            <div class="col-lg-10 col-md-9">
                                <input type="text" id="txtCantidad" class="form-control" placeholder="Articulo" value="@Model.Cantidad" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-9 col-md-9 control-label" for="">Precio</label>
                            <div class="col-lg-10 col-md-9">
                                <input type="text" id="txtPrecio" disabled class="form-control" placeholder="Articulo" value="@Model.Precio" />
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-lg-9 col-md-9 control-label" for="">Total</label>
                            <div class="col-lg-10 col-md-9">
                                <input type="text" id="txtTotal" disabled class="form-control" placeholder="Articulo" value="@Model.Total" />
                            </div>
                        </div>

                        <div class="form-group">
                            <button class="btn btn-success" style="width:100px" onclick="guardarVenta()">Guardar cambios</button>
                            <button class="btn btn-danger" style="width:100px" onclick="eliminarVenta()">Eliminar Venta</button>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#datetimepicker2").datetimepicker({
            format: 'L'
        });
    });

    function eliminarVenta() {
        var _idVenta = $("#txtIdVenta").val();

        var urlSave = '@Url.Action("EliminarVenta", "Ventas")';
        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ idVenta: _idVenta }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                alert("Venta eliminada ");
            },
            error: function (result) {
                alert("Woops, se produjo un error");
            }
        });
    }

    function guardarVenta() {
        var _idVenta = $("#txtIdVenta").val();
        var _fecha = $("#datetimepicker2").data("date");
        var _cantidad = $("#txtCantidad").val();
        var _idArticulo = $("#cboArticulos").val();
        var _idPromotor = $("#cboPromotores").val();
        var urlSave = '@Url.Action("GuardarCambiosVenta", "Ventas")';
        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ idVenta: _idVenta, cantidad: _cantidad, fecha: _fecha, idArticulo: _idArticulo, idPromotor: _idPromotor }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                alert("Cambios guardados correctamente ");

                var link = "@Url.Action("Index","Ventas")";
                window.location.href = link;

            },
            error: function (result) {
                alert("Woops, se produjo un error");
            }
        });
    }

</script>

ViewERP/WebView/Views/Ventas/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Mis ventas de esta semana</h4>
                <hr />
                <div style="overflow-x:auto;">
                    <table class="table align-items-center table-flush table-borderless">
                        <thead>
                            <tr>
                                <th>ARTICULO</th>
                                <th>CANTIDAD</th>
                                <th>PRECIO</th>
                                <th>TOTAL</th>
                                <th>FECHA</th>
                                <th>PROMOTOR</th>
                            </tr>
                        </thead>
                        <tbody id="tblVentas"></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        var urlSave = '@Url.Action("GetVentasCurrentWeek", "Ventas")';
        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ parametro: "" }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                var row = "";
                $.each(data, function (index, item) {
                    row += "<tr>";
                    row += "<td><a href=\"@Url.Action("Edit", "Ventas")?id=" + item.IdVenta + "\">" + item.Nombre + "</a> </td>";
                    row += "<td>" + item.Cantidad + "</td>";
                    row += "<td>$" + item.Precio + "</td>";
                    row += "<td>$" + item.Total + "</td>";
                    row += "<td>" + item.sFecha + "</td>";
                    row += "<td>" + item.NombrePromotor + "</td>";
                    row += "</tr>";
                });
                $("#tblVentas").append(row);
            },
            error: function (result) {
                alert("Woops, se produjo un error");
            }
        });
    });
</script>