ViewERP/WebView/Controllers/OrganizacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebView.Models;

namespace WebView.Controllers
{
    public class OrganizacionController : Controller
    {
        // GET: Organizacion
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetOrganizacion(string parametro)
        {
            DO_Persona personaConectada = ((DO_Persona)Session["UsuarioConectado"]);
            List<DO_OrganizationChart> miOrganizacion = DataManager.GetMiOrganizacion(personaConectada.idUsuario);

            var jsonResult = Json(miOrganizacion, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
    }
}

ViewERP/WebView/Views/Organizacion/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    #chart_div .google-visualization-orgchart-linebottom {
        border-bottom: 4px solid #0ea156;
    }

    #chart_div .google-visualization-orgchart-lineleft {
        border-left: 4px solid #0ea156;
    }

    #chart_div .google-visualization-orgchart-lineright {
        border-right: 4px solid #0ea156;
    }

    #chart_div .google-visualization-orgchart-linetop {
        border-top: 4px solid #0ea156;
    }
</style>

<h2>Mi Organización</h2>

<div class="row">

    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                Mi Organización
            </div>
            <div class="card-body">
                <div id="chart_div"  style="overflow-x:auto;"></div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

<script type="text/javascript">
    google.charts.load('current', { packages: ["orgchart"] });
    google.charts.setOnLoadCallback(drawChart);

    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('string', 'Name');
        data.addColumn('string', 'Manager');
        data.addColumn('string', 'ToolTip');

        var urlSave = '@Url.Action("GetOrganizacion", "Organizacion")';
        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ parametro: "" }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (informacion) {
                var c = 0;
                $.each(informacion, function (index, item) {
                    var idUsuario = '' + item.Yo.idUsuario;
                    var idJefe = '' + item.Yo.IdJefe;

                    if (c == 0) {
                        data.addRow([{ v: idUsuario, f: item.Yo.Nombre + '<div style="color:tomato; font-style:italic">' + item.Yo.Rol + '</div>' }, '', item.Yo.Rol]);
                    } else {
                        if (item.Yo.Rol == "GERENTE" || item.Yo.Rol == "GERENTE PROMOTOR") {
                            data.addRow([{ v: idUsuario, f: '<div><a href="@Url.Action("IndexByGerente","Home")?id=' + item.Yo.idUsuario + '">' + item.Yo.Nombre + '</a></div> <div style="color:tomato; font-style:italic">' + item.Yo.Rol + '</div> ' }, idJefe, item.Yo.Nombre]);
                        } else if (item.Yo.Rol == "PROMOTOR" || item.Yo.Rol == "SUPERVISOR" || item.Yo.Rol == "SUPERVISOR ELITE" || item.Yo.Rol == "ASISTENTE") {
                            //data.addRow([{ v: idUsuario, f: '<div><a href="@Url.Action("Editar","Promotores")?id=' + item.Yo.idUsuario + '">' + item.Yo.Nombre + '</a></div> <div style="color:tomato; font-style:italic">' + item.Yo.Rol + '</div> ' }, idJefe, item.Yo.Nombre]);
                        }
                    }
                    c++;
                });
            },
            error: function (result) {
                alert("Woops, se produjo un error");
            },
            complete: function (d) {
                var chart = new google.visualization.OrgChart(document.getElementById('chart_div'));

                chart.draw(data, { 'allowHtml': true, 'allowCollapse': true, 'size': 'large', color: '#000000', selectionColor: '#bcab31' });
            }
        });
    }
</script>