ViewERP/WebView/Controllers/CreateAccountController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebView.Models;

namespace WebView.Controllers
{
    public class CreateAccountController : Controller
    {
        public ActionResult Create()
        {
            ViewBag.Personas = DataManager.GetPosiblesJefes();
            return View();
        }

        [HttpPost]
        public JsonResult CrearCuenta(string nombre, string email, string contrasena, string telefono, string direccion, int idRol, int idJefe)
        {

            DO_Persona dO_Persona1 =  DataManager.GetPersona(email);

            if (dO_Persona1.ID_ROL == 2 || dO_Persona1.idUsuario == 0)
            {
                //Se establece el plan de 7 dias libres por default.
                int idPlan = 1;
                int idCompania = DataManager.InsertCompania(nombre, "RFC", direccion, telefono, email, idPlan);

                if (idCompania > 0)
                {
                    DO_Persona dO_Persona = new DO_Persona();
                    dO_Persona.Nombre = nombre;
                    dO_Persona.ApellidoMaterno = string.Empty;
                    dO_Persona.ApellidoPaterno = string.Empty;
                    dO_Persona.idCompania = idCompania;
                    dO_Persona.ID_ROL = idRol;
                    dO_Persona.Contrasena = contrasena;
                    dO_Persona.Usuario = email;
                    dO_Persona.IdJefe = idJefe;

                    int r = DataManager.InsertPersona(dO_Persona);

                    DO_Almacen almacen = new DO_Almacen();
                    almacen.idCompania = idCompania;
                    almacen.Nombre = "Mi Bodega";
                    almacen.Descripcion = "Esta es mi bodega";

                    int rAlmacen = DataManager.InsertAlmacen(almacen);

                    DO_CategoriaArticulo categoriaArticulo = new DO_CategoriaArticulo();

                    categoriaArticulo.idCompania = idCompania;
                    categoriaArticulo.NombreCategoria = "ARTICULOS DE VENTA";
                    categoriaArticulo.numeroCategoria = "01";

                    int c = DataManager.InsertCategoriaArticulo(categoriaArticulo);

                    //DO_Persona jefe = DataManager.GetPersona(idJefe);
                    //List<DO_Articulo> articulosJefe = DataManager.GetAllArticulos(jefe.idCompania);
                    //foreach (var articulo in articulosJefe)
                    //{
                    //    articulo.idCompania = idCompania;
                    //    articulo.ID_CATEGORIA = c;
                    //    articulo.Codigo = DataManager.GetNextCodigoArticulo(Convert.ToString(c));
                    //    int idArticulo = DataManager.InsertArticulo(articulo);
                    //    DataManager.InsertDetailsArticulo(idArticulo, articulo.PRECIO_UNIDAD, articulo.PRECIO_MASTER, articulo.PRECIO_PROMOTOR, articulo.PRECIO_GERENTE);
                    //}

                    DO_CategoriaArticulo categoriaArticulo1 = new DO_CategoriaArticulo();
                    categoriaArticulo1.idCompania = idCompania;
                    categoriaArticulo1.NombreCategoria = "OTROS";
                    categoriaArticulo1.numeroCategoria = "02";

                    c = DataManager.InsertCategoriaArticulo(categoriaArticulo1);

                    if (idRol == 3)
                    {
                        DataManager.InsertOrganizacion(idCompania, "ORG." + nombre);
                    }

                    DataManager.InsertBitacora("Usuario anónimo", "Se creó una cuenta con el correo: " + dO_Persona.Usuario);

                    var jsonResult = Json("Cuenta activada exitosamente", JsonRequestBehavior.AllowGet);
                    jsonResult.MaxJsonLength = int.MaxValue;

                    return jsonResult;
                }
            }
            else
            {
                var jsonResult = Json("El correo ya existe, por favor ingresa otro.", JsonRequestBehavior.AllowGet);
                jsonResult.MaxJsonLength = int.MaxValue;

                return jsonResult;
            }

            return null;
        }
    }
}

ViewERP/WebView/Controllers/LogInController.cs
using Model;
using System.Web.Mvc;
using WebView.Models;

namespace WebView.Controllers
{
    public class LogInController : Controller
    {
        // GET: LogIn
        [ERPVerificaRol]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Ingresar([Bind(Include = "Usuario,Contrasena")] DO_Persona persona)
        {
            if (ModelState.IsValid)
            {
                DO_Persona usuario = DataManager.GetLogin(persona.Usuario, persona.Contrasena);
                if (usuario != null)
                {
                    Session["UsuarioConectado"] = usuario;
                    Session["NombrePersona"] = usuario.NombreCompleto;
                    Session["CorreoPersona"] = usuario.Usuario;

                    Session["GERENTE"] = false;
                    Session["CONTACTO"] = false;
                    Session["PRODUCCION"] = false;
                    Session["ADMINISTRADOR"] = false;
                    Session["GERENTE_PROMOTOR"] = false;

                    switch (usuario.ID_ROL)
                    {
                        case 1:
                            Session["GERENTE"] = true;
                            break;
                        case 2:
                            Session["CONTACTO"] = true;
                            break;
                        case 3:
                            Session["GERENTE_PROMOTOR"] = true;
                            break;
                        case 4:
                            Session["PRODUCCIÓN"] = true;
                            break;
                        case 5:
                            Session["ADMINISTRADOR"] = true;
                            break;
                        default:
                            break;
                    }

                    DO_Organizacion organizacion = DataManager.GetOrganizacionByIdCompania(usuario.idCompania);

                    Session["IS_ORGANIZACION"] = organizacion.IdOrganizacion != 0 ? true : false;
                    usuario.idOrganizacion = organizacion.IdOrganizacion;

                    int r = DataManager.InsertBitacora(usuario.NombreCompleto + " " + usuario.Usuario, "INGRESA A LA PLATAFORMA");

                    return RedirectToAction("Index", "Home");
                }
                else
                    return View("Index");
            }
            else
                return View("Index");
        }
    }
}

ViewERP/WebView/Views/CreateAccount/Create.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashtreme Admin - Free Dashboard for Bootstrap 4 by Codervent</title>
    <!-- loader-->
    @*<link href="@Url.Content("assets/css/pace.min.css")" rel="stylesheet" />
    <script src="@Url.Content("assets/js/pace.min.js")"></script>*@
    <!--favicon-->
    <link rel="icon" href="@Url.Content("~/assets/images/favicon.ico")" type="image/x-icon">
    <!-- Bootstrap core CSS-->
    <link href="@Url.Content("~/assets/css/bootstrap.min.css")" rel="stylesheet" />
    <!-- animate CSS-->
    <link href="@Url.Content("~/assets/css/animate.css")" rel="stylesheet" type="text/css" />
    <!-- Icons CSS-->
    <link href="@Url.Content("~/assets/css/icons.css")" rel="stylesheet" type="text/css" />
    <!-- Custom Style-->
    <link href="@Url.Content("~/assets/css/app-style.css")" rel="stylesheet" />

</head>

<body class="bg-theme bg-theme1">

    <!-- start loader -->
    <div id="pageloader-overlay" class="visible incoming"><div class="loader-wrapper-outer"><div class="loader-wrapper-inner"><div class="loader"></div></div></div></div>
    <!-- end loader -->
    <!-- Start wrapper-->
    <div id="wrapper">

        <div class="card card-authentication1 mx-auto my-4">
            <div class="card-body">
                <div class="card-content p-2">
                    <div class="text-center">
                        <img src="@Url.Content("~/assets/images/logo-icon.png")" alt="logo icon">
                    </div>
                    <div class="card-title text-uppercase text-center py-3">Crea tu cuenta</div>
                    <form>
                        <div class="form-group">
                            <label for="exampleInputName" class="sr-only">Nombre</label>
                            <div class="position-relative has-icon-right">
                                <input type="text" id="txtNombre" class="form-control input-shadow" placeholder="Ingresa tu nombre">
                                <div class="form-control-position">
                                    <i class="icon-user"></i>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmailId" class="sr-only">Email ID</label>
                            <div class="position-relative has-icon-right">
                                <input type="text" id="txtEmail" class="form-control input-shadow" placeholder="Ingresa tu correo">
                                <div class="form-control-position">
                                    <i class="icon-envelope-open"></i>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <select id="cboPerfil" class="form-control">
                                <option value="0" selected>Selecciona un perfil</option>
                                <option value="1">Gerente</option>
                                <option value="3">Gerente Promotor</option>
                            </select>
                        </div>

                        <div class="form-group">
                            <label>Reporto a</label>
                            <select id="cboJefes" class="form-control">
                                @{
                                    foreach (SelectListItem persona in ((List<SelectListItem>)ViewBag.Personas))
                                    {
                                        if (persona.Selected)
                                        {
                                            <option selected id="@persona.Value" value="@persona.Value">@persona.Text</option>
                                        }
                                        else
                                        {
                                            <option id="@persona.Value" value="@persona.Value">@persona.Text</option>
                                        }

                                    }
                                }
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputName" class="sr-only">Telefono</label>
                            <div class="position-relative has-icon-right">
                                <input type="text" id="txtTelefono" class="form-control input-shadow" placeholder="Ingresa tu teléfono">
                                <div class="form-control-position">
                                    <i class="icon-phone"></i>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputName" class="sr-only">Dirección</label>
                            <div class="position-relative has-icon-right">
                                <input type="text" id="txtDireccion" class="form-control input-shadow" placeholder="Ingresa tu dirección">
                                <div class="form-control-position">
                                    <i class="fa fa-address-book"></i>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputPassword" class="sr-only">Password</label>
                            <div class="position-relative has-icon-right">
                                <input type="password" id="txtContrasena" class="form-control input-shadow" maxlength="8" placeholder="Ingresa tu contraseña">
                                <div class="form-control-position">
                                    <i class="icon-lock"></i>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="icheck-material-white">
                                <input type="checkbox" id="user-checkbox" checked="" />
                                <label for="user-checkbox">Estoy de acuerdo con los terminos y condiciones</label>
                            </div>
                        </div>

                        <button type="button" onclick="crearCuenta()" class="btn btn-light btn-block waves-effect waves-light">Crear cuenta</button>

                    </form>
                </div>
            </div>
            <div class="card-footer text-center py-3">
                <p class="text-warning mb-0">¿Ya tienes cuenta? <a href="@Url.Action("Index","LogIn")"> Ingresa aquí</a></p>
            </div>
        </div>

        <!--Start Back To Top Button-->
        <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
        <!--End Back To Top Button-->

    </div><!--wrapper-->
    <!-- Bootstrap core JavaScript-->
    <script src="@Url.Content("~/assets/js/jquery.min.js")"></script>
    <script src="@Url.Content("~/assets/js/popper.min.js")"></script>
    <script src="@Url.Content("~/assets/js/bootstrap.min.js")"></script>

    <!-- sidebar-menu js -->
    <script src="@Url.Content("~/assets/js/sidebar-menu.js")"></script>

    <!-- Custom scripts -->
    <script src="@Url.Content("~/assets/js/app-script.js")"></script>

    <script type="text/javascript">
        function crearCuenta() {
            if (validarFormulario()) {
                var _nombre = $("#txtNombre").val();
                var _email = $("#txtEmail").val();
                var _contrasena = $("#txtContrasena").val();
                var _telefono = $("#txtTelefono").val();
                var _direccion = $("#txtDireccion").val();
                var _perfil = $("#cboPerfil").val();
                var _idJefe = $("#cboJefes").val();

                var urlSave = '@Url.Action("CrearCuenta", "CreateAccount")';
                $.ajax({
                    type: "POST",
                    url: urlSave,
                    data: JSON.stringify({ nombre: _nombre, email: _email, contrasena: _contrasena, telefono: _telefono, direccion: _direccion, idRol: _perfil, idJefe: _idJefe }),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (data) {
                        alert(data);
                        if (data == "Cuenta activada exitosamente") {
                            var url = '@Url.Action("Ingresar", "LogIn")';
                            window.location.href = url;
                        }
                    },
                    error: function (result) {
                        alert("Woops, se produjo un error");
                    }
                });
            } else {

            }
        }

        function validarFormulario() {
            var _nombre = $("#txtNombre").val();
            var _email = $("#txtEmail").val();
            var _contrasena = $("#txtContrasena").val();
            var _telefono = $("#txtTelefono").val();
            var _direccion = $("#txtDireccion").val();
            var _perfil = $("#cboPerfil").val();
            var _idJefe = $("#cboJefes").val();

            if (_idJefe == 0) {
                alert("Por favor indica a quien reportas directamente");
                return false;
            }

            if (_perfil == 0) {
                alert("Por favor seleccione un perfil");
                return false;
            }

            if (_contrasena.length != 8) {
                alert("La contraseña debe ser de 8 digitos");
                return false;
            }

            if (_nombre == "" || _email == "" || _contrasena == "" || _telefono == "" || _direccion == "") {
                alert("Favor ingresar toda la información");
                return false;
            }
            return true;
        }
    </script>

</body>
</html>