ViewERP/WebView/Controllers/AdministracionERPController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebView.Models;

namespace WebView.Controllers
{
    public class AdministracionERPController : Controller
    {
        [ERPVerificaRol]
        public ActionResult Index()
        {
            return View();
        }

        [ERPVerificaRol]
        [HttpPost]
        public JsonResult RealizarCorteAlmacen(string parametro)
        {
            string respuesta = string.Empty;
            DO_Persona personaConectada = ((DO_Persona)Session["UsuarioConectado"]);

            int a = DataManager.SetCorteAlmacenes(personaConectada.Nombre + " "+ personaConectada.Usuario);

            if(a > 0)
            {
                respuesta = "Corte establecido correctamente. " + a + " registros modificados.";
            }
            else
            {
                respuesta = "Hubo un error, por favor intente mas tarde.";
            }

            var jsonResult = Json(respuesta, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }

        [HttpPost]
        public JsonResult GetAllUsuarios(string parametro)
        {
            List<DO_Persona> usuarios = DataManager.GetAllPersona();

            var jsonResult = Json(usuarios, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;

            return jsonResult;
        }
    }
}

ViewERP/WebView/Views/AdministracionERP/Index.cshtml
 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Administración ERP</h2>
<div class="row">
    <button class="btn btn-success" id="btnGuardarCorteAlmacen" onclick="corteAlmacen()">Realizar Corte Almacen</button>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Usuarios</h4>
                <hr />
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table align-items-center table-flush table-borderless">
                            <thead>
                                <tr>
                                    <th>NOMBRE</th>
                                    <th>USUARIO</th>
                                    <th>COMPAÑIA</th>
                                    <th>ROL</th>
                                    <th>PLAN</th>
                                    <th>FECHA ALTA</th>
                                </tr>
                            </thead>
                            <tbody id="tblUsuarios">
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>NOMBRE</th>
                                    <th>USUARIO</th>
                                    <th>COMPAÑIA</th>
                                    <th>ROL</th>
                                    <th>PLAN</th>
                                    <th>FECHA ALTA</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    $(document).ajaxStart(function () {
        $("#btnGuardarCorteAlmacen").addClass("disabled");
        $("#btnGuardarCorteAlmacen").html("<i class=\"fa fa-refresh fa-spin\"></i>Guardando");
    });

    $(document).ajaxComplete(function () {
        $("#btnGuardarCorteAlmacen").html("Realizar Corte Almacen");
        $("#btnGuardarCorteAlmacen").removeClass("disabled");
    });

    $(document).ready(function () {
        var urlSave = '@Url.Action("GetAllUsuarios", "AdministracionERP")';

        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ parametro: "" }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                var row = "";

                $.each(data, function (index, item) {
                    row += "<tr>";
                    row += "<td>" + item.Nombre + "</td>";
                    row += "<td>" + item.Usuario + "</td>";
                    row += "<td>" + item.NombreCompania + "</td>";
                    row += "<td>" + item.Rol + "</td>";
                    row += "<td>" + item.NombrePlan + "</td>";
                    row += "<td>" + item.SFechaRegistro + "</td>";
                    row += "</tr>";
                });

                $("#tblUsuarios").append(row);
            },
            error: function (result) {
                alert(result);
            }
        });
    });

    function corteAlmacen() {
        var urlSave = '@Url.Action("RealizarCorteAlmacen", "AdministracionERP")';

        $.ajax({
            type: "POST",
            url: urlSave,
            data: JSON.stringify({ parametro: "" }),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                alert(data);
            },
            error: function (result) {
                alert(result);
            }
        });
    }
</script>